### ISSUE TITLE
Will you provide simplified environments?

### ISSUE THREAD

**Issue by GoingMyWay** [Unity-Technologies/ml-agents-dodgeball-env#4]
Hi, this is really awesome. For beginners, Unity3D is not easy to learn. Will you provide simplified environments?

**Comment by ervteng** [comment]
Hey @GoingMyWay, we believe Unity3D is totally worth the learning curve! There's a good set of easy environments that Unity and LEGO made to get started (https://learn.unity.com/project/lego-template).

**Comment by GoingMyWay** [comment]
> Hey @GoingMyWay, we believe Unity3D is totally worth the learning curve! There's a good set of easy environments that Unity and LEGO made to get started (https://learn.unity.com/project/lego-template).

Thank you.
